projetemargement/src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PromotionRepository::class)
 */
class Promotion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PromotionName;


    /**
     * @ORM\OneToMany(targetEntity=TimeSlot::class, mappedBy="Promotion")
     */
    private $timeSlots;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="promotions")
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private User $author;

    public function __construct()
    {
        $this->timeSlots = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPromotionName(): ?string
    {
        return $this->PromotionName;
    }

    public function setPromotionName(string $PromotionName): self
    {
        $this->PromotionName = $PromotionName;

        return $this;
    }

    /**
     * @return Collection|TimeSlot[]
     */
    public function getTimeSlots(): Collection
    {
        return $this->timeSlots;
    }

    public function addTimeSlot(TimeSlot $timeSlot): self
    {
        if (!$this->timeSlots->contains($timeSlot)) {
            $this->timeSlots[] = $timeSlot;
            $timeSlot->setPromotion($this);
        }

        return $this;
    }

    public function removeTimeSlot(TimeSlot $timeSlot): self
    {
        if ($this->timeSlots->removeElement($timeSlot)) {
            // set the owning side to null (unless already changed)
            if ($timeSlot->getPromotion() === $this) {
                $timeSlot->setPromotion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->users->removeElement($user);

        return $this;
    }

    public function __toString(): string
    {
        return $this->PromotionName;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
}

projetemargement/src/Form/PromotionType.php
<?php

namespace App\Form;

use App\Entity\Promotion;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('PromotionName')
            ->add('users', EntityType::class, [
                'class'    => User::class,
                'expanded' => true,
                'multiple' => true,
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Créer une promotion'
            ]);;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

projetemargement/src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Promotion;
use App\Form\PromotionType;
use App\Repository\PromotionRepository;
use App\Repository\UserRepository;
use App\Security\Voter\FormationEditVoter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class PromotionController
 * @package App\Controller
 *
 * @Route("/promotion")
 * @IsGranted ("ROLE_ADMIN")
 *
 * @author Mélanie Engrand
 */
class PromotionController extends AbstractController
{
    /**
     * @Route("/", name="promotion_index", methods={"GET"})
     * @IsGranted ("ROLE_ADMIN")
     * @param PromotionRepository $promotionRepository
     * @return Response
     */
    public function index(PromotionRepository $promotionRepository): Response
    {
        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="promotion_new", methods={"GET","POST"})
     * @IsGranted ("ROLE_ADMIN")
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $this->denyAccessUnlessGranted(FormationEditVoter::CREATE);

        $promotion = new Promotion();
        $me = $this->getUser();

        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $promotion->setAuthor($me);
            $entityManager->persist($promotion);
            $entityManager->flush();

            return $this->redirectToRoute('promotion_index');
        }

        return $this->render('promotion/new.html.twig', [
            'promotion' => $promotion,
            'form'      => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="promotion_show", methods={"GET"})
     * @IsGranted ("ROLE_ADMIN")
     * @param int $id
     * @param Promotion $promotion
     * @param UserRepository $userRepository
     * @param PromotionRepository $promotionRepository
     * @return Response
     */
    public function show(int $id, Promotion $promotion, UserRepository $userRepository, PromotionRepository $promotionRepository): Response
    {
        $promo = $promotionRepository->find($id);
        $usersPromo = $userRepository->findByFormationForPerson($promo);

        return $this->render('promotion/show.html.twig', [
            'promotion'  => $promotion,
            'usersPromo' => $usersPromo
        ]);
    }

    /**
     * @Route("/{id}/edit", name="promotion_edit", methods={"GET","POST"})
     * @IsGranted ("ROLE_ADMIN")
     * @param Request $request
     * @param Promotion $promotion
     * @return Response
     */
    public function edit(Request $request, Promotion $promotion): Response
    {
        $this->denyAccessUnlessGranted(FormationEditVoter::UPDATE);
        $this->denyAccessUnlessGranted(FormationEditVoter::UPDATE_TRAINING, $promotion);

        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('promotion_index');
        }

        return $this->render('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form'      => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="promotion_delete", methods={"POST"})
     * @IsGranted ("ROLE_ADMIN")
     * @param Request $request
     * @param Promotion $promotion
     * @return Response
     */
    public function delete(Request $request, Promotion $promotion): Response
    {
        if ($this->isCsrfTokenValid('delete' . $promotion->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($promotion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('promotion_index');
    }
}

projetemargement/templates/promotion/_delete_form.html.twig
<form method="post" action="{{ path('promotion_delete', {'id': promotion.id}) }}" onsubmit="return confirm('Etes vous sûr de vouloir supprimer cette formation ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.id) }}">
    <button class="btn-delete">Supprimer</button>
</form>

projetemargement/templates/promotion/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form.users, {'attr': {'class': 'users'}}) }}
{{ form_end(form) }}
    <button class="btn-option">
        <div class="btn-action-hover"{{ button_label|default('Savegarder') }}>Sauvegarder</div>
    </button></br>

projetemargement/templates/promotion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier {{ promotion.promotionName }}{% endblock %}

{% block body %}
    <h1>Modifier {{ promotion.promotionName }}</h1>
    {{ include('promotion/_form.html.twig', {'button_label': 'Update'}) }}
    <button class="btn-option">
        <a class="btn-action-hover" href="{{ path('promotion_index') }}">Retourner à la liste</a>
    </button>
    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}

projetemargement/templates/promotion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion{% endblock %}

{% block body %}
    <h1>Liste des promotions</h1>

    <a href="{{ path('promotion_new') }}"> +Créer une nouvelle formation</a>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom de la formation</th>
                <th>Créateur de la formation</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for promotion in promotions %}
            <tr>
                <td>{{ promotion.id }}</td>
                <td>{{ promotion.PromotionName }}</td>
                <td>{{ promotion.author }}</td>
                <td>
                <a class="btn-action" href="{{ path('promotion_show', {'id': promotion.id}) }}">Voir</a>
                    {% if promotion.author == app.user %}
                        <a class="btn-action" href="{{ path('promotion_edit', {'id': promotion.id}) }}">Modifier</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('promotion_new') }}">Créer une nouvelle formation</a>
{% endblock %}

projetemargement/templates/promotion/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer une nouvelle promotion{% endblock %}

{% block body %}
    <h1>Créer une nouvelle promotion</h1>

    {{ form_start(form) }}
        {{ form_widget(form.users, {'attr': {'class': 'users'}}) }}
    {{ form_end(form) }}

    <a href="{{ path('promotion_index') }}">Retourner à la liste</a>
{% endblock %}

projetemargement/templates/promotion/show.html.twig
{# author Mélanie Engrand #}
{% extends 'base.html.twig' %}

{% block title %}Promotion {{ promotion.promotionName }}{% endblock %}

{% block body %}
    <h1>Promotion {{ promotion.promotionName}}</h1></br>
    <h2>Liste des apprenants pour cette promotion</h2>
    {% for user in usersPromo %}
        {{ user.firstname }} - {{ user.lastname }} </br>
    {% endfor %} 
    </br><h2>Détail de la promotion</h2>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ promotion.id }}</td>
            </tr>
            <tr>
                <th>PromotionName</th>
                <td>{{ promotion.PromotionName }}</td>
            </tr>
        </tbody>
    </table>
    <button class="btn-option">
        <a class="btn-action-hover" href="{{ path('promotion_index') }}">Retourner à la liste des promotions</a>
    </button>
    </br>
    {% if promotion.author == app.user %}
        <button class="btn-option">
            <a class="btn-action-hover" href="{{ path('promotion_edit', {'id': promotion.id}) }}">Modifier</a>
        </button>
        {{ include('promotion/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}