projetemargement/src/Entity/TimeSlot.php
<?php

namespace App\Entity;

use App\Repository\TimeSlotRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TimeSlotRepository::class)
 */
class TimeSlot
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Start;

    /**
     * @ORM\Column(type="datetime")
     */
    private $End;

    /**
     * @ORM\Column(type="integer")
     */
    private $Code;

    /**
     * @ORM\OneToMany(targetEntity=Validation::class, mappedBy="TimeSlot", cascade={"remove"})
     */
    private $validations;

    /**
     * @ORM\ManyToOne(targetEntity=Promotion::class, inversedBy="timeSlots")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Promotion;

    public function __construct()
    {
        $this->validations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?int
    {
        return $this->Code;
    }

    public function setCode(int $Code): self
    {
        $this->Code = $Code;

        return $this;
    }

    /**
     * @return Collection|Validation[]
     */
    public function getValidations(): Collection
    {
        return $this->validations;
    }

    public function addValidation(Validation $validation): self
    {
        if (!$this->validations->contains($validation)) {
            $this->validations[] = $validation;
            $validation->setTimeSlot($this);
        }

        return $this;
    }

    public function removeValidation(Validation $validation): self
    {
        if ($this->validations->removeElement($validation)) {
            // set the owning side to null (unless already changed)
            if ($validation->getTimeSlot() === $this) {
                $validation->setTimeSlot(null);
            }
        }

        return $this;
    }

    public function getPromotion(): ?Promotion
    {
        return $this->Promotion;
    }

    public function setPromotion(?Promotion $Promotion): self
    {
        $this->Promotion = $Promotion;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->End;
    }

    public function setEnd(\DateTimeInterface $End): self
    {
        $this->End = $End;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->Start;
    }

    public function setStart(\DateTimeInterface $Start): self
    {
        $this->Start = $Start;

        return $this;
    }
    public function __toString(): string
    {
        return $this->Code;
    }
}

projetemargement/src/Entity/Validation.php
<?php

namespace App\Entity;

use App\Repository\ValidationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ValidationRepository::class)
 */
class Validation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Presence;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="validations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=TimeSlot::class, inversedBy="validations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $TimeSlot;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPresence(): ?string
    {
        return $this->Presence;
    }

    public function setPresence(string $Presence): self
    {
        $this->Presence = $Presence;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTimeSlot(): ?TimeSlot
    {
        return $this->TimeSlot;
    }

    public function setTimeSlot(?TimeSlot $TimeSlot): self
    {
        $this->TimeSlot = $TimeSlot;

        return $this;
    }

}

projetemargement/src/Form/TimeSlotType.php
<?php

namespace App\Form;

use App\Entity\TimeSlot;
use Doctrine\DBAL\Types\IntegerType;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Promotion;

class TimeSlotType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Start', DateTimeType::class)
            ->add('End', DateTimeType::class)
            ->add('Promotion', EntityType::class, [
                'class' => Promotion::class,
                'choice_label' => 'promotion_name',
                'query_builder' => function (EntityRepository $er){
                return $er->createQueryBuilder('p')->orderBy('p.PromotionName', 'ASC');
                }
            ])
            ->add('Repeat', NumberType::class, [
                'required'   => false,
                'mapped' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
    }
}

projetemargement/src/Controller/TimeSlotController.php
<?php

namespace App\Controller;

use App\Entity\TimeSlot;
use App\Form\TimeSlotType;
use App\Repository\TimeSlotRepository;
use App\Repository\ValidationRepository;
use DateInterval;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class TimeSlotController
 * @package App\Controller
 *
 * @Route("/time_slot")
 *
 * @author Mélanie Engrand
 */
class TimeSlotController extends AbstractController
{
    /**
     * @Route("/", name="time_slot_index", methods={"GET"})
     * @IsGranted ("ROLE_MANAGER")
     * @param TimeSlotRepository $timeSlotRepository
     * @return Response
     */
    public function index(TimeSlotRepository $timeSlotRepository): Response
    {
        return $this->render('time_slot/index.html.twig', [
            'time_slots' => $timeSlotRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="time_slot_new", methods={"GET","POST"})
     * @IsGranted ("ROLE_ADMIN")
     * @param Request $request
     * @return Response
     * @throws \Exception
     */
    public function new(Request $request): Response
    {
        /*dump($request->request->get("time_slot")['Repeat']);*/
        $form = $this->createForm(TimeSlotType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $start = $data["Start"];
            $end = $data["End"];
            $promo = $data["Promotion"];
            $repeat = $request->request->get("time_slot")['Repeat'];
            $repeat++;
            for ($i = 0; $i < $repeat; $i++) {
                $timeSlot = new TimeSlot();
                $entityManager = $this->getDoctrine()->getManager();
                $code = random_int(10000, 99999);
                $timeSlot->setCode($code);
                $timeSlot->setStart($start);
                $timeSlot->setEnd($end);
                $timeSlot->setPromotion($promo);
                $entityManager->persist($timeSlot);
                $entityManager->flush();
                $start->add(new DateInterval('P7D'));
                $end->add(new DateInterval('P7D'));
            }

            return $this->redirectToRoute('time_slot_index');
        }

        return $this->render('time_slot/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="time_slot_show", methods={"GET"})
     * @IsGranted ("ROLE_MANAGER")
     * @param int $id
     * @param TimeSlot $timeSlot
     * @param ValidationRepository $validationRepository
     * @param TimeSlotRepository $timeSlotRepository
     * @return Response
     */
    public function show(int $id, TimeSlot $timeSlot, ValidationRepository $validationRepository, TimeSlotRepository $timeSlotRepository): Response
    {
        $timeSlot = $timeSlotRepository->find($id);
        $timeslotvalidation = $validationRepository->findByValidationForTimeslot($timeSlot);
        return $this->render('time_slot/show.html.twig', [
            'time_slot'          => $timeSlot,
            'timeslotvalidation' => $timeslotvalidation
        ]);
    }

    /**
     * @Route("/{id}/edit", name="time_slot_edit", methods={"GET","POST"})
     * @IsGranted ("ROLE_ADMIN")
     * @param Request $request
     * @param TimeSlot $timeSlot
     * @return Response
     */
    public function edit(Request $request, TimeSlot $timeSlot): Response
    {
        $form = $this->createForm(TimeSlotType::class, $timeSlot);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('time_slot_index');
        }

        return $this->render('time_slot/edit.html.twig', [
            'time_slot' => $timeSlot,
            'form'      => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="time_slot_delete", methods={"POST"})
     * @IsGranted ("ROLE_ADMIN")
     * @param Request $request
     * @param TimeSlot $timeSlot
     * @return Response
     */
    public function delete(Request $request, TimeSlot $timeSlot): Response
    {
        if ($this->isCsrfTokenValid('delete' . $timeSlot->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($timeSlot);
            $entityManager->flush();
        }

        return $this->redirectToRoute('time_slot_index');
    }
}

projetemargement/templates/time_slot/_delete_form.html.twig
<form method="post" action="{{ path('time_slot_delete', {'id': time_slot.id}) }}" onsubmit="Etes vous sûr de vouloir supprimer ce créneau ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ time_slot.id) }}">
    <button class="btn-delete">Delete</button>
</form>

projetemargement/templates/time_slot/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn-option">
        <div class="btn-action-hover"{{ button_label|default('Savegarder') }}>Sauvegarder</div>
        </button>
{{ form_end(form) }}

projetemargement/templates/time_slot/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier {{ time_slot.id }}{% endblock %}

{% block body %}
    <h1>Modifier le créneau {{ time_slot.id }}</h1>
    {{ include('time_slot/_form.html.twig') }}
    <button class="btn-option">
        <a class="btn-action-hover" href="{{ path('time_slot_index') }}">Retourner à la liste</a>
    </button>

    {{ include('time_slot/_delete_form.html.twig') }}
{% endblock %}

projetemargement/templates/time_slot/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creneaux{% endblock %}

{% block body %}
    <h1>Liste de tous les créneaux</h1>
    {% if is_granted('ROLE_ADMIN')%}
        <a href="{{ path('time_slot_new') }}"> + Créer un nouveau créneau</a>
    {% endif %}
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Début</th>
                <th>Fin</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for time_slot in time_slots %}
            <tr>
                <td>{{ time_slot.id }}</td>
                <td>{{ time_slot.Start ? time_slot.Start|date('H:i:s d-m-Y') : '' }}</td>
                <td>{{ time_slot.End ? time_slot.End|date('H:i:s d-m-Y') : '' }}</td>
                <td>
                    <a class="btn-action" href="{{ path('time_slot_show', {'id': time_slot.id}) }}">Voir</a>
                    {% if is_granted('ROLE_ADMIN')%}
                        <a class="btn-action" href="{{ path('time_slot_edit', {'id': time_slot.id}) }}">Modifier</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_ADMIN')%}
        <a class="new_time_slot_link" href="{{ path('time_slot_new') }}"> + Créer un nouveau créneau</a>
    {% endif %}
{% endblock %}

projetemargement/templates/time_slot/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau créneau{% endblock %}

{% block body %}
    <h1>Créer un nouveau créneau</h1>

    {{ include('time_slot/_form.html.twig') }}
    <button class="btn-option">
        <a class="btn-action-hover" href="{{ path('time_slot_index') }}">Retourner à la liste des créneaux</a>
    </button>
{% endblock %}

projetemargement/templates/time_slot/show.html.twig
{# author Mélanie Engrand #}

{% extends 'base.html.twig' %}

{% block title %}Creneau {{ time_slot.id }}{% endblock %}

{% block body %}
    <h1>Créneau {{ time_slot.id }}</h1>
    <h2>Liste des apprenants pour ce créneau</h2>     
    <table class="table">
        <tbody>
            <tr>
                <th>Apprenant</th>
                <th>Présence</th>
            </tr>
            {% for validation in timeslotvalidation %}
                <tr>
                    <td> {{ validation.user }} </td>
                    <td> {{ validation.presence }}</td>
                </tr>
            {% endfor %}
    </br>
    <table class="table">
    <h2>Créneaux</h2>
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ time_slot.id }}</td>
            </tr>
            <tr>
                <th>Début</th>
                <td>{{ time_slot.Start ? time_slot.Start|date('H:i:s d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Fin</th>
                <td>{{ time_slot.End ? time_slot.End|date('H:i:s d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Code</th>
                <td>{{ time_slot.Code }}</td>
            </tr>
        </tbody>
    </table>
    <button class="btn-option">
        <a class="btn-action-hover" href="{{ path('time_slot_index') }}">Retourner à la liste des utilisateurs</a>
    </button>
    </br>
    {% if is_granted('ROLE_ADMIN')%}
        <button class="btn-option">
            <a class="btn-action-hover" href="{{ path('time_slot_edit', {'id': time_slot.id}) }}">modifier</a>
        </button>
    {% endif %}
    {% if is_granted('ROLE_ADMIN')%}
        {{ include('time_slot/_delete_form.html.twig') }}
    {% endif %}</br>
{% endblock %}